[terminal]
vt = next

[default_session]
command = "env GTK_USE_PORTAL=0 GDK_DEBUG=no-portals LIBSEAT_BACKEND=seatd XKB_DEFAULT_LAYOUT=us,ru XKB_DEFAULT_OPTIONS=grp:win_space_toggle,compose:ralt,ctrl:nocaps dbus-run-session cage -s -m last -d -- regreet"
user = "_greeter"
